### ISSUE TITLE
please make it part of boost library

### ISSUE THREAD

**Issue by congzhangzh** [tobias-loew/windows_thunks#2]
Why not make it part of boost c++ library, it is needed by some people:)

**Comment by tobias-loew** [comment]
~~I'm on it. I'll present it in the next days to the boost mailing list.
Feel free to vote for it 🙂~~
Sorry, I replied from my mobile and thought it was about my https://github.com/tobias-loew/flags library, which I will present within the next days. When I'm through with that, I'll ask whether there's interest in this library.

**Comment by congzhangzh** [comment]
@tobias-loew Hi Tobias, your solution even works with lambda and std::function objects, I add a demo here:

https://github.com/tobias-loew/windows_thunks/pull/3

I try to do some OpenGL projects these days, you thunk solution was really working very well as OpenGL callback:)

Refs:
<https://github.com/congzhangzh/hello_cg>
